### ISSUE TITLE
Various Syringe sizes simultaneously

### ISSUE THREAD

**Issue by YTayyar** [Vsaggiomo/Ender3-syringe-pumps#3]
Hi and Thank you for the amazing work.
Is it possible to use different syringe pumps on the different channels at once?
Also, can you specify a certain flow rate for each channel at the same time?

**Comment by Vsaggiomo** [comment]
Yes, it is possible to use different syringes on different pumps, you just need to change the M92 commands, and yes it is possible to use different flow rates for each channel. From our paper: 
________
Multiple syringes can be used at the same time:

G1 X0.5 Y0.5 Z0.5 F1

Will deliver, at the same time, 0.5 mL of liquid from the pumps on X, Y, and Z at a speed of 1 mL/min

For using different flow speed for different pumps, the total amount of liquid should be calculated taking in account that all the pumps will reach the end at the same time. For example:

G1 X2 Y1 Z2 F1

Will deliver the set amount of liquid at different flow speed, using 1 mL/min on Y, and 2 mL/min on X and Z.
__________
