### ISSUE TITLE
Functionality Based on Direction

### ISSUE THREAD

**Issue by NikiW94** [Vsaggiomo/Ender3-syringe-pumps#5]
I am having issues getting the pump to function properly. I am 99% certain that it is exclusively a g-code problem, not something wrong with the actual assembly. First of all, for my first test of the system, I used the example g-code in the operating instructions* and only one of the three pumps (E) functioned. The other two did not rotate at all. The E pump, however, followed the code just fine. In my second test, I changed this line: M92 X-20927 Y-20927 Z20927 to this: M92 X20927 Y20927 Z20927 and kept the rest the same. All three pumps moved, but, as noted in the article, X & Y moved backward. In another test, I used the following code:
; 5 mL syringes on the three pumps
M92 X33663 Y33663 Z33663 ; set the proper steps/mL for the 5mL syringe
M302 S0 ; print without checking temperature
G91 ; relative positioning
; deliver 1mL at 2mL/min sequentially
G1 X1 F2
G1 Y1 F2
G1 Z1 F2
This time X & Y still moved backward but pump E did not move. Then, again, when I modified the first line to be M92 X-33663 Y-33663 Z33663, none of the pumps worked. I don't see another way to change the direction of the X & Y pumps without making them stop. Any suggestions would be highly appreciated.

____________________________________________________________________________________
*M92 X-20927 Y-20927 Z20927 ; set the proper steps/mL for the 10mL syringe
M302 S0 ; print without checking temperature
G91 ; relative positioning
; deliver 1mL at 2mL/min sequentially
G1 X1 F2
G1 Y1 F2
G1 Z1 F2
; wait for 10 seconds
G4 S10
; deliver 1mL on X and Z at 1mL/min, 2mL on Y at 2mL/min
G1 X1 Y2 Z1 F1
; wait 10 seconds
G4 S10
; deliver 1mL at 2mL/min sequentially
G1 Z1 F2
G1 Y1 F2
G1 X1 F2

**Comment by Vsaggiomo** [comment]
well, juts to be pragmatic and make the system work, you can keep the M92 positive and then move the X Y motors in negative :) 
M92 X33663 Y33663 Z33663
M302 S0 ; print without checking temperature
G91 ; relative positioning
G1 X-1 F2
G1 Y-1 F2
G1 Z1 F2

then you talk about the E motor, but in none of the example you wrote, you use it (G1 E), so, not sure about that. 

to solve the problem once for all, my guess is that is a text editor problem (try to use notepad++) as gcode files may be annoyed by some hidden characters (for example there is - and – which are two different characters)
I'd say, try to connect the motherboard with prontface and give the commands one by one and check where is the problem.

**Comment by NikiW94** [comment]
Hello. Thanks for your response. Just to clarify, in my first comment when I referred to pump "E" in the g-code it is designated as pump "Z" but the cable is labeled as "E". I will refer to it as pump Z moving forward. 

I have a new set of questions based on experimentation/troubleshooting that I have done today. 

First of all, sometimes when something goes wrong the LCD displays "Heating failed PRINTER HALTED Please reset". The only way I have found to "reset" the system is to turn it off and back on. Is there another method? Or is that practice okay? Has this ever occurred when you were initially testing the pump?

Second, I connected the system to Pronterface as you suggested and I think I understand the problem, but I have no idea how to resolve it. I began by inputting M92 X33663 Y33663 Z 33663. Then M302 S0 and G91. After those were all sent, I input G1 X1 F2. That worked just fine; the motor was just inverted as before. Then I tried G1 X-1 F2 and received this error message: 

echo: endstops
hit: X:1.00

I understood this to mean the system doesn't know where it is in space, so I clicked the home button just to see what would happen and all three motors emitted this grinding sound and didn't rotate smoothly so I killed that command. 

In another test I input M92 X-33663 Y-33663 Z33663, M302 S0, G91, which all sent without throwing any errors. After G1 X1 F2, I then received the following message:

echo: endstops
hit: X:0.00

In the last test I input M92 X33663 Y33663 Z33663, M302 S0, G91, and G1 X1 Y2 Z1 F1. That worked (inverted again), but when I changed the last instruction to G1 X-1 Y-2 Z1 F1, I got:

echo: endstops 
hit:  X:3.00 Y:4.00

Also, I don't know if this is relevant, but each time Pronterface threw and error, I could hear the motors switch on but none of the pumps moved. 

I wondered if you had any insight as to how I can fix this. Thanks.

**Comment by Vsaggiomo** [comment]
I see, you missed: 
M211 S0 ; print without checking the end stops 
it should go after the M302 S0 
:) 

please tell me if this fixed it so I can close this issue

**Comment by NikiW94** [comment]
So, I added M211 S0 to the line up so my test code now looks like this:

M92 X33663 Y33663 Z33663
M302 S0
M211 S0
G91
G1 X-1 F2

And I am still thrown this error message:

echo: endstops hit:  X:1.00

In case it is relevant, when I a sent M211 S0 into Pronterface, it returned:

echo: Soft endstops: Off  

Did I do something wrong? For further context, if I input G1 X1 F2 it still runs, just backwards as before.

I appreciate your help.

**Comment by Vsaggiomo** [comment]
ok, that's weird, what happens if you give the commands line by line in pronterface?
are you sure the physical endstops are not installed? 
or you can try M121 before the M211 S0 

also, in pronterface can you send an M115 and tell me which firmware is installed there?

**Comment by NikiW94** [comment]
The system that I physically built was done so using the provided instructions. I took no creative liberties. When you say physical endstops do you mean the motor mount and syringe mount 3d printed pieces?

>>> M92 X33663 Y33663 Z33663
SENDING:M92 X33663 Y33663 Z33663
>>> M302 S0
SENDING:M302 S0
>>> M211 S0
SENDING:M211 S0
echo:Soft endstops: Off  Min: X0.00 Y0.00 Z0.00  Max: X235.00 Y235.00 Z250.00
>>> G91
SENDING:G91
>>> G1 X-1 F2
SENDING:G1 X-1 F2
echo:endstops hit:  X:7.00

Above is everything I just put into Pronterface and the returned messages. 

Below is everything I get when I input M115:

>>> M115
SENDING:M115
FIRMWARE_NAME:Marlin Creality 3D SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender-3 EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Cap:EEPROM:1
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:0
Cap:Z_PROBE:0
Cap:LEVELING_DATA:0
Cap:SOFTWARE_POWER:0
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:0

I also tried: 
; 10 mL syringes on the three pumps
M92 X-20927 Y-20927 Z20927 ; set the proper steps/mL for the 10mL syringe
M302 S0 ; print without checking temperature
M121
M211 S0 ; print without endstops
G91 ; relative positioning
; deliver 1mL at 2mL/min sequentially
G1 X1 F2
G1 Y1 F2
G1 Z1 F2

This, I am happy to report, worked just fine. The only problem with the above is that I have to load it into Pronterface for it to function. If I save it on a microSD and print it using the LCD, the Z pump doesn't move. Don't know what that's about. But I suppose I can just use it tethered to a computer.

**Comment by Vsaggiomo** [comment]
Perfect, then I'll close it here. For the SD card, I'm 99% sure it's a text formatting thing. You should have no spaces or weird characters (they may be invisible, but happens because of copy/paste). And you need to use a proper text editor, like notepad ++ . In notepad ++ you need to use "UNIX" end of the line:
 End of Line (EOL) characters used on Windows vs Unix. Using Edit > EOL Conversion > Unix (LF), to switch to the Unix EOF character.

**Comment by Vsaggiomo** [comment]
Summary: 
weirdly enough, this combo firmware/board had a problem with the endstops, and they were triggered even if the M211 S0 (print without soft end stop) was in there. 
The command M121 (Disable endstops) did the trick and the pumps work correctly now
